### ISSUE TITLE
automatically check updated yaml files against schema

### ISSUE THREAD

**Issue by tychonievich** [FamilySearch/GEDCOM-registries#37]
Add a github action that checks changes YAML files as a status check, and require passing that status check before merging

**Comment by dthaler** [comment]
https://stackoverflow.com/questions/71334373/is-there-a-way-i-can-validate-yaml-files-on-github

**Comment by tychonievich** [comment]
Clarification: in addition to valid yaml (addressed by #40) we also should check the contents of the repo (not the github actions, etc) against https://github.com/FamilySearch/GEDCOM-registries/blob/main/registry_tools/yaml-schema.yaml
